if underch.have_lootchests_default then
	local items = {
		{"underch:sword_emerald"},
		{"underch:pick_emerald"},
		{"underch:shovel_emerald"},
		{"underch:axe_emerald"},
		{"underch:sword_ruby"},
		{"underch:pick_ruby"},
		{"underch:shovel_ruby"},
		{"underch:axe_ruby"},
		{"underch:sword_saphire"},
		{"underch:pick_saphire"},
		{"underch:shovel_saphire"},
		{"underch:axe_saphire"},
	}

	if underch.have_x_bows then
		table.insert(items, {"underch:arrow_emerald"})
		table.insert(items, {"underch:arrow_ruby"})
		table.insert(items, {"underch:arrow_saphire"})
	end

	if underch.have_3d_armor then
		table.insert(items, {"underch:helmet_emerald"})
		table.insert(items, {"underch:chestplate_emerald"})
		table.insert(items, {"underch:leggings_emerald"})
		table.insert(items, {"underch:boots_emerald"})
		table.insert(items, {"underch:helmet_ruby"})
		table.insert(items, {"underch:chestplate_ruby"})
		table.insert(items, {"underch:leggings_ruby"})
		table.insert(items, {"underch:boots_ruby"})
		table.insert(items, {"underch:helmet_saphire"})
		table.insert(items, {"underch:chestplate_saphire"})
		table.insert(items, {"underch:leggings_saphire"})
		table.insert(items, {"underch:boots_saphire"})
	end

	if underch.have_shields then
		table.insert(items, {"underch:shield_emerald"})
		table.insert(items, {"underch:shield_ruby"})
		table.insert(items, {"underch:shield_saphire"})
	end

	lootchests.add_to_loot_table("lootchests_default:ocean_chest", items)
	lootchests.add_to_loot_table("lootchests_default:urn", items)
	lootchests.add_to_loot_table("lootchests_default:stone_chest", items)
	lootchests.add_to_loot_table("lootchests_default:basket", items)
	lootchests.add_to_loot_table("lootchests_default:barrel", items)
end

if underch.have_dungeon_loot then
	dungeon_loot.register({
		{name = "underch:sword_emerald", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
		{name = "underch:pick_emerald", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
		{name = "underch:shovel_emerald", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
		{name = "underch:axe_emerald", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
		{name = "underch:sword_ruby", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
		{name = "underch:pick_ruby", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
		{name = "underch:shovel_ruby", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
		{name = "underch:axe_ruby", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
		{name = "underch:sword_saphire", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
		{name = "underch:pick_saphire", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
		{name = "underch:shovel_saphire", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
		{name = "underch:axe_saphire", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
	})

	if underch.have_x_bows then
		dungeon_loot.register({
			{name = "underch:arrow_emerald", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
			{name = "underch:arrow_ruby", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
			{name = "underch:arrow_saphire", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
		})
	end

	if underch.have_3d_armor then
		dungeon_loot.register({
			{name = "underch:helmet_emerald", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
			{name = "underch:chestplate_emerald", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
			{name = "underch:leggings_emerald", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
			{name = "underch:boots_emerald", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
			{name = "underch:helmet_ruby", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
			{name = "underch:chestplate_ruby", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
			{name = "underch:leggings_ruby", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
			{name = "underch:boots_ruby", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
			{name = "underch:helmet_saphire", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
			{name = "underch:chestplate_saphire", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
			{name = "underch:leggings_saphire", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
			{name = "underch:boots_saphire", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
		})
	end

	if underch.have_shields then
		dungeon_loot.register({
			{name = "underch:shield_emerald", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
			{name = "underch:shield_ruby", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
			{name = "underch:shield_saphire", chance = 0.1, count = {1, 1}, y = {-31000, 31000}},
		})
	end
end

if underch.have_bones_loot then
	bones_loot.register_loot({
		{name = "underch:sword_emerald", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
		{name = "underch:pick_emerald", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
		{name = "underch:shovel_emerald", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
		{name = "underch:axe_emerald", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
		{name = "underch:sword_ruby", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
		{name = "underch:pick_ruby", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
		{name = "underch:shovel_ruby", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
		{name = "underch:axe_ruby", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
		{name = "underch:sword_saphire", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
		{name = "underch:pick_saphire", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
		{name = "underch:shovel_saphire", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
		{name = "underch:axe_saphire", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
	})

	if underch.have_x_bows then
		bones_loot.register_loot({
			{name = "underch:arrow_emerald", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
			{name = "underch:arrow_ruby", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
			{name = "underch:arrow_saphire", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
		})
	end

	if underch.have_3d_armor then
		bones_loot.register_loot({
			{name = "underch:helmet_emerald", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
			{name = "underch:chestplate_emerald", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
			{name = "underch:leggings_emerald", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
			{name = "underch:boots_emerald", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
			{name = "underch:helmet_ruby", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
			{name = "underch:chestplate_ruby", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
			{name = "underch:leggings_ruby", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
			{name = "underch:boots_ruby", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
			{name = "underch:helmet_saphire", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
			{name = "underch:chestplate_saphire", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
			{name = "underch:leggings_saphire", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
			{name = "underch:boots_saphire", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
		})
	end

	if underch.have_shields then
		bones_loot.register_loot({
			{name = "underch:shield_emerald", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
			{name = "underch:shield_ruby", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
			{name = "underch:shield_saphire", chance = 0.1, count = {1, 1}, types = {"underworld_warrior"}},
		})
	end
end

if underch.have_handle_schematics then
	table.insert(handle_schematics.random_chest_content, {
		"underch:sword_emerald",
		1,
		1,
		1,
		chest_default = 1,
		farm_tiny = 1,
		farm_full = 1,
		shed = 1,
		hut = 1,
		chest_work = 1,
		lumberjack = 1,
		forge = 1,
		guard = 1,
		ship = 1,
		church = 1,
		library = 1,
		chest_private = 1,
		wreck = 1,
		tavern = 1,
		inn = 1,
		bakery = 1,
		shelf = 1,
	})

	table.insert(handle_schematics.random_chest_content, {
		"underch:pick_emerald",
		1,
		1,
		1,
		chest_default = 1,
		farm_tiny = 1,
		farm_full = 1,
		shed = 1,
		hut = 1,
		chest_work = 1,
		lumberjack = 1,
		forge = 1,
		guard = 1,
		ship = 1,
		church = 1,
		library = 1,
		chest_private = 1,
		wreck = 1,
		tavern = 1,
		inn = 1,
		bakery = 1,
		shelf = 1,
	})

	table.insert(handle_schematics.random_chest_content, {
		"underch:shovel_emerald",
		1,
		1,
		1,
		chest_default = 1,
		farm_tiny = 1,
		farm_full = 1,
		shed = 1,
		hut = 1,
		chest_work = 1,
		lumberjack = 1,
		forge = 1,
		guard = 1,
		ship = 1,
		church = 1,
		library = 1,
		chest_private = 1,
		wreck = 1,
		tavern = 1,
		inn = 1,
		bakery = 1,
		shelf = 1,
	})

	table.insert(handle_schematics.random_chest_content, {
		"underch:axe_emerald",
		1,
		1,
		1,
		chest_default = 1,
		farm_tiny = 1,
		farm_full = 1,
		shed = 1,
		hut = 1,
		chest_work = 1,
		lumberjack = 1,
		forge = 1,
		guard = 1,
		ship = 1,
		church = 1,
		library = 1,
		chest_private = 1,
		wreck = 1,
		tavern = 1,
		inn = 1,
		bakery = 1,
		shelf = 1,
	})

	table.insert(handle_schematics.random_chest_content, {
		"underch:sword_ruby",
		1,
		1,
		1,
		chest_default = 1,
		farm_tiny = 1,
		farm_full = 1,
		shed = 1,
		hut = 1,
		chest_work = 1,
		lumberjack = 1,
		forge = 1,
		guard = 1,
		ship = 1,
		church = 1,
		library = 1,
		chest_private = 1,
		wreck = 1,
		tavern = 1,
		inn = 1,
		bakery = 1,
		shelf = 1,
	})

	table.insert(handle_schematics.random_chest_content, {
		"underch:pick_ruby",
		1,
		1,
		1,
		chest_default = 1,
		farm_tiny = 1,
		farm_full = 1,
		shed = 1,
		hut = 1,
		chest_work = 1,
		lumberjack = 1,
		forge = 1,
		guard = 1,
		ship = 1,
		church = 1,
		library = 1,
		chest_private = 1,
		wreck = 1,
		tavern = 1,
		inn = 1,
		bakery = 1,
		shelf = 1,
	})

	table.insert(handle_schematics.random_chest_content, {
		"underch:shovel_ruby",
		1,
		1,
		1,
		chest_default = 1,
		farm_tiny = 1,
		farm_full = 1,
		shed = 1,
		hut = 1,
		chest_work = 1,
		lumberjack = 1,
		forge = 1,
		guard = 1,
		ship = 1,
		church = 1,
		library = 1,
		chest_private = 1,
		wreck = 1,
		tavern = 1,
		inn = 1,
		bakery = 1,
		shelf = 1,
	})

	table.insert(handle_schematics.random_chest_content, {
		"underch:axe_ruby",
		1,
		1,
		1,
		chest_default = 1,
		farm_tiny = 1,
		farm_full = 1,
		shed = 1,
		hut = 1,
		chest_work = 1,
		lumberjack = 1,
		forge = 1,
		guard = 1,
		ship = 1,
		church = 1,
		library = 1,
		chest_private = 1,
		wreck = 1,
		tavern = 1,
		inn = 1,
		bakery = 1,
		shelf = 1,
	})

	table.insert(handle_schematics.random_chest_content, {
		"underch:sword_saphire",
		1,
		1,
		1,
		chest_default = 1,
		farm_tiny = 1,
		farm_full = 1,
		shed = 1,
		hut = 1,
		chest_work = 1,
		lumberjack = 1,
		forge = 1,
		guard = 1,
		ship = 1,
		church = 1,
		library = 1,
		chest_private = 1,
		wreck = 1,
		tavern = 1,
		inn = 1,
		bakery = 1,
		shelf = 1,
	})

	table.insert(handle_schematics.random_chest_content, {
		"underch:pick_saphire",
		1,
		1,
		1,
		chest_default = 1,
		farm_tiny = 1,
		farm_full = 1,
		shed = 1,
		hut = 1,
		chest_work = 1,
		lumberjack = 1,
		forge = 1,
		guard = 1,
		ship = 1,
		church = 1,
		library = 1,
		chest_private = 1,
		wreck = 1,
		tavern = 1,
		inn = 1,
		bakery = 1,
		shelf = 1,
	})

	table.insert(handle_schematics.random_chest_content, {
		"underch:shovel_saphire",
		1,
		1,
		1,
		chest_default = 1,
		farm_tiny = 1,
		farm_full = 1,
		shed = 1,
		hut = 1,
		chest_work = 1,
		lumberjack = 1,
		forge = 1,
		guard = 1,
		ship = 1,
		church = 1,
		library = 1,
		chest_private = 1,
		wreck = 1,
		tavern = 1,
		inn = 1,
		bakery = 1,
		shelf = 1,
	})

	table.insert(handle_schematics.random_chest_content, {
		"underch:axe_saphire",
		1,
		1,
		1,
		chest_default = 1,
		farm_tiny = 1,
		farm_full = 1,
		shed = 1,
		hut = 1,
		chest_work = 1,
		lumberjack = 1,
		forge = 1,
		guard = 1,
		ship = 1,
		church = 1,
		library = 1,
		chest_private = 1,
		wreck = 1,
		tavern = 1,
		inn = 1,
		bakery = 1,
		shelf = 1,
	})

	if underch.have_x_bows then
		table.insert(handle_schematics.random_chest_content, {
			"underch:arrow_emerald",
			1,
			1,
			1,
			chest_default = 1,
			farm_tiny = 1,
			farm_full = 1,
			shed = 1,
			hut = 1,
			chest_work = 1,
			lumberjack = 1,
			forge = 1,
			guard = 1,
			ship = 1,
			church = 1,
			library = 1,
			chest_private = 1,
			wreck = 1,
			tavern = 1,
			inn = 1,
			bakery = 1,
			shelf = 1,
		})

		table.insert(handle_schematics.random_chest_content, {
			"underch:arrow_ruby",
			1,
			1,
			1,
			chest_default = 1,
			farm_tiny = 1,
			farm_full = 1,
			shed = 1,
			hut = 1,
			chest_work = 1,
			lumberjack = 1,
			forge = 1,
			guard = 1,
			ship = 1,
			church = 1,
			library = 1,
			chest_private = 1,
			wreck = 1,
			tavern = 1,
			inn = 1,
			bakery = 1,
			shelf = 1,
		})

		table.insert(handle_schematics.random_chest_content, {
			"underch:arrow_saphire",
			1,
			1,
			1,
			chest_default = 1,
			farm_tiny = 1,
			farm_full = 1,
			shed = 1,
			hut = 1,
			chest_work = 1,
			lumberjack = 1,
			forge = 1,
			guard = 1,
			ship = 1,
			church = 1,
			library = 1,
			chest_private = 1,
			wreck = 1,
			tavern = 1,
			inn = 1,
			bakery = 1,
			shelf = 1,
		})
	end

	if underch.have_3d_armor then
		table.insert(handle_schematics.random_chest_content, {
			"underch:helmet_emerald",
			1,
			1,
			1,
			chest_default = 1,
			farm_tiny = 1,
			farm_full = 1,
			shed = 1,
			hut = 1,
			chest_work = 1,
			lumberjack = 1,
			forge = 1,
			guard = 1,
			ship = 1,
			church = 1,
			library = 1,
			chest_private = 1,
			wreck = 1,
			tavern = 1,
			inn = 1,
			bakery = 1,
			shelf = 1,
		})

		table.insert(handle_schematics.random_chest_content, {
			"underch:chestplate_emerald",
			1,
			1,
			1,
			chest_default = 1,
			farm_tiny = 1,
			farm_full = 1,
			shed = 1,
			hut = 1,
			chest_work = 1,
			lumberjack = 1,
			forge = 1,
			guard = 1,
			ship = 1,
			church = 1,
			library = 1,
			chest_private = 1,
			wreck = 1,
			tavern = 1,
			inn = 1,
			bakery = 1,
			shelf = 1,
		})

		table.insert(handle_schematics.random_chest_content, {
			"underch:leggings_emerald",
			1,
			1,
			1,
			chest_default = 1,
			farm_tiny = 1,
			farm_full = 1,
			shed = 1,
			hut = 1,
			chest_work = 1,
			lumberjack = 1,
			forge = 1,
			guard = 1,
			ship = 1,
			church = 1,
			library = 1,
			chest_private = 1,
			wreck = 1,
			tavern = 1,
			inn = 1,
			bakery = 1,
			shelf = 1,
		})

		table.insert(handle_schematics.random_chest_content, {
			"underch:boots_emerald",
			1,
			1,
			1,
			chest_default = 1,
			farm_tiny = 1,
			farm_full = 1,
			shed = 1,
			hut = 1,
			chest_work = 1,
			lumberjack = 1,
			forge = 1,
			guard = 1,
			ship = 1,
			church = 1,
			library = 1,
			chest_private = 1,
			wreck = 1,
			tavern = 1,
			inn = 1,
			bakery = 1,
			shelf = 1,
		})

		table.insert(handle_schematics.random_chest_content, {
			"underch:helmet_ruby",
			1,
			1,
			1,
			chest_default = 1,
			farm_tiny = 1,
			farm_full = 1,
			shed = 1,
			hut = 1,
			chest_work = 1,
			lumberjack = 1,
			forge = 1,
			guard = 1,
			ship = 1,
			church = 1,
			library = 1,
			chest_private = 1,
			wreck = 1,
			tavern = 1,
			inn = 1,
			bakery = 1,
			shelf = 1,
		})

		table.insert(handle_schematics.random_chest_content, {
			"underch:chestplate_ruby",
			1,
			1,
			1,
			chest_default = 1,
			farm_tiny = 1,
			farm_full = 1,
			shed = 1,
			hut = 1,
			chest_work = 1,
			lumberjack = 1,
			forge = 1,
			guard = 1,
			ship = 1,
			church = 1,
			library = 1,
			chest_private = 1,
			wreck = 1,
			tavern = 1,
			inn = 1,
			bakery = 1,
			shelf = 1,
		})

		table.insert(handle_schematics.random_chest_content, {
			"underch:leggings_ruby",
			1,
			1,
			1,
			chest_default = 1,
			farm_tiny = 1,
			farm_full = 1,
			shed = 1,
			hut = 1,
			chest_work = 1,
			lumberjack = 1,
			forge = 1,
			guard = 1,
			ship = 1,
			church = 1,
			library = 1,
			chest_private = 1,
			wreck = 1,
			tavern = 1,
			inn = 1,
			bakery = 1,
			shelf = 1,
		})

		table.insert(handle_schematics.random_chest_content, {
			"underch:boots_ruby",
			1,
			1,
			1,
			chest_default = 1,
			farm_tiny = 1,
			farm_full = 1,
			shed = 1,
			hut = 1,
			chest_work = 1,
			lumberjack = 1,
			forge = 1,
			guard = 1,
			ship = 1,
			church = 1,
			library = 1,
			chest_private = 1,
			wreck = 1,
			tavern = 1,
			inn = 1,
			bakery = 1,
			shelf = 1,
		})

		table.insert(handle_schematics.random_chest_content, {
			"underch:helmet_saphire",
			1,
			1,
			1,
			chest_default = 1,
			farm_tiny = 1,
			farm_full = 1,
			shed = 1,
			hut = 1,
			chest_work = 1,
			lumberjack = 1,
			forge = 1,
			guard = 1,
			ship = 1,
			church = 1,
			library = 1,
			chest_private = 1,
			wreck = 1,
			tavern = 1,
			inn = 1,
			bakery = 1,
			shelf = 1,
		})

		table.insert(handle_schematics.random_chest_content, {
			"underch:chestplate_saphire",
			1,
			1,
			1,
			chest_default = 1,
			farm_tiny = 1,
			farm_full = 1,
			shed = 1,
			hut = 1,
			chest_work = 1,
			lumberjack = 1,
			forge = 1,
			guard = 1,
			ship = 1,
			church = 1,
			library = 1,
			chest_private = 1,
			wreck = 1,
			tavern = 1,
			inn = 1,
			bakery = 1,
			shelf = 1,
		})

		table.insert(handle_schematics.random_chest_content, {
			"underch:leggings_saphire",
			1,
			1,
			1,
			chest_default = 1,
			farm_tiny = 1,
			farm_full = 1,
			shed = 1,
			hut = 1,
			chest_work = 1,
			lumberjack = 1,
			forge = 1,
			guard = 1,
			ship = 1,
			church = 1,
			library = 1,
			chest_private = 1,
			wreck = 1,
			tavern = 1,
			inn = 1,
			bakery = 1,
			shelf = 1,
		})

		table.insert(handle_schematics.random_chest_content, {
			"underch:boots_saphire",
			1,
			1,
			1,
			chest_default = 1,
			farm_tiny = 1,
			farm_full = 1,
			shed = 1,
			hut = 1,
			chest_work = 1,
			lumberjack = 1,
			forge = 1,
			guard = 1,
			ship = 1,
			church = 1,
			library = 1,
			chest_private = 1,
			wreck = 1,
			tavern = 1,
			inn = 1,
			bakery = 1,
			shelf = 1,
		})
	end

	if underch.have_shields then
		table.insert(handle_schematics.random_chest_content, {
			"underch:shield_emerald",
			1,
			1,
			1,
			chest_default = 1,
			farm_tiny = 1,
			farm_full = 1,
			shed = 1,
			hut = 1,
			chest_work = 1,
			lumberjack = 1,
			forge = 1,
			guard = 1,
			ship = 1,
			church = 1,
			library = 1,
			chest_private = 1,
			wreck = 1,
			tavern = 1,
			inn = 1,
			bakery = 1,
			shelf = 1,
		})

		table.insert(handle_schematics.random_chest_content, {
			"underch:shield_ruby",
			1,
			1,
			1,
			chest_default = 1,
			farm_tiny = 1,
			farm_full = 1,
			shed = 1,
			hut = 1,
			chest_work = 1,
			lumberjack = 1,
			forge = 1,
			guard = 1,
			ship = 1,
			church = 1,
			library = 1,
			chest_private = 1,
			wreck = 1,
			tavern = 1,
			inn = 1,
			bakery = 1,
			shelf = 1,
		})

		table.insert(handle_schematics.random_chest_content, {
			"underch:shield_saphire",
			1,
			1,
			1,
			chest_default = 1,
			farm_tiny = 1,
			farm_full = 1,
			shed = 1,
			hut = 1,
			chest_work = 1,
			lumberjack = 1,
			forge = 1,
			guard = 1,
			ship = 1,
			church = 1,
			library = 1,
			chest_private = 1,
			wreck = 1,
			tavern = 1,
			inn = 1,
			bakery = 1,
			shelf = 1,
		})
	end
end
